# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=50)),
                ('activity_periods', models.ManyToManyField(to='user_activities.ActivityPeriod')),
            ],
        ),
    ]
