# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0002_auto_20200806_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.CharField(max_length=50),
        ),
    ]
